config/routes.rb
Rails.application.routes.draw do
  resources :ethograms

  # routes for devise users
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get '/export/observations', controller: :observation_exports, action: :index

  namespace :api do
    resources :ethograms, only: :index
    resources :observation_sessions, only: :create
    post :auth, controller: :auth, action: :create
  end

  root to: 'home#index'

  resources :users, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ethogram.rb
# frozen_string_literal: true

class Ethogram < ApplicationRecord
  validates_presence_of :name
  has_many :ethogram_structures

  def current_ethogram_structure
    @_current_ethogram_structure ||= ethogram_structures.order(:created_at).last
  end

  delegate :structure, to: :current_ethogram_structure, allow_nil: true

  def structure_id
    current_ethogram_structure&.id
  end

  def subjects
    structure&.fetch('subjects', [])
  end

  def behaviors
    structure&.fetch('behaviors', [])
  end

  def structure=(form)
    form = JSON.parse(form) if form.is_a?(String)
    ethogram_structures.build(structure: form)
  end
end

app/models/ethogram_structure.rb
class EthogramStructure < ApplicationRecord
  belongs_to :ethogram
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :observation_session

  def self.latest
    order(created_at: :desc).first
  end

  comma do
    id 'id'
    observation_session_id 'observation_session_id'
    observation_session user_id: 'user_id'
    observation_session('user_email') { |os| os.user&.email }
    details('subject') { |d| d['subject'] }
    details('modifier') { |d| d['modifier'] }
    details('behavior') { |d| d['behavior'] }
    details('target') { |d| d['target'] }
    details('timestamp') { |d| d['timestamp'] }
  end
end

app/models/observation_session.rb
class ObservationSession < ApplicationRecord
  has_many :observations
  belongs_to :user

  def self.create_once(attrs)
    find_or_create_by!(attrs)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  def token
    JWT.encode \
      jwt_token_payload,
      Rails.application.secrets.secret_key_base,
      'HS256'
  end

  def self.authenticate_jwt(jwt)
    decoded_token = JWT.decode jwt, Rails.application.secrets.secret_key_base, true, algorithm: 'HS256'
    find_by(id: decoded_token['id'])
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user if user && user.valid_password?(password)
  end

  private def jwt_token_payload
    @_jwt_token_payload ||= {
      id: id,
      email: email
    }
  end
end

app/controllers/api/auth_controller.rb
module Api
  class AuthController < BaseController
    skip_before_action :authenticate!

    def create
      user = current_user || User.authenticate(params[:email], params[:password])
      if user
        render json: { jwt_token: user.token }
      else
        unauthorized
      end
    end
  end
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::Base
    before_action :authenticate!

    def authenticate!
      unauthorized unless current_user
    end

    def unauthorized
      render json: { msg: 'You are not authorized' }, status: :unauthorized
    end

    def current_user
      token = request.headers['AUTHORIZATION'].to_s.split(' ').last
      if token
        payload = JWT.decode token, Rails.application.secrets.secret_key_base, true, algorithm: 'HS256'
        @_current_user ||= User.find_by(id: payload.first['id'])
      end
    end

    helper_method :current_user
  end
end

app/controllers/api/ethograms_controller.rb
# frozen_string_literal: true

module Api
  class EthogramsController < BaseController
    def index
      render json: { data: Ethogram.all.as_json(
        only: %i[id name],
        methods: %i[subjects behaviors structure_id]
      ) }
    end
  end
end

app/controllers/api/observation_sessions_controller.rb
# frozen_string_literal: true

module Api
  class ObservationSessionsController < BaseController
    def create
      ActiveRecord::Base.transaction do
        session_ids_to_instances = {}

        processed_observations = observations_params.map do |observation|
          session = session_ids_to_instances.fetch(observation['observation_session_id']) do |session_id|
            session_ids_to_instances[session_id] = ObservationSession.find_or_create_by(id: session_id, user_id: current_user.id)
          end

          Observation.find_or_create_by(id: observation['id']) do |record|
            record.details = observation
            record.observation_session = session
          end
        end

        response = processed_observations.map { |o| { id: o.id, persisted: o.persisted?, errors: o.errors.full_messages } }
        render json: response, status: :ok
      end
    rescue ActiveRecord::StatementInvalid => e
      render json: { msg: e.message }, status: 422
    end

    private

    def observations_params
      params.fetch('observations', [])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/ethograms_controller.rb
class EthogramsController < ApplicationController
  before_action :set_ethogram, only: %i[show edit update destroy]

  # GET /ethograms
  def index
    @ethograms = Ethogram.all
  end

  # GET /ethograms/1
  def show; end

  # GET /ethograms/new
  def new
    @ethogram = Ethogram.new
  end

  # GET /ethograms/1/edit
  def edit; end

  # POST /ethograms
  def create
    @ethogram = Ethogram.new(ethogram_params)

    if @ethogram.save
      redirect_to @ethogram, notice: 'Ethogram was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ethograms/1
  def update
    if @ethogram.update(ethogram_params)
      redirect_to @ethogram, notice: 'Ethogram was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ethograms/1
  def destroy
    @ethogram.destroy
    redirect_to ethograms_url, notice: 'Ethogram was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ethogram
    @ethogram = Ethogram.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def ethogram_params
    params.require(:ethogram).permit(:name, :structure)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @num_observations = Observation.count
    @latest_observation = Observation.latest
  end
end

app/controllers/observation_exports_controller.rb
class ObservationExportsController < ApplicationController
  def index
    @observations = Observation.all
    respond_to do |format|
      format.csv { render :csv => @observations }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.where.not(id: current_user.id)
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url, notice: t('notices.destroy', model_name: @user.email)
  end
end

app/helpers/api/auth_helper.rb
module Api::AuthHelper
end

app/helpers/api/observation_sessions_helper.rb
module Api::ObservationSessionsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  FLASH_MESSAGE_CLASSES = { success: 'alert-success',
                            error: 'alert-danger',
                            alert: 'alert-warning',
                            notice: 'alert-info' }.stringify_keys.freeze

  def bootstrap_class_for(flash_type)
    FLASH_MESSAGE_CLASSES[flash_type] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ethograms/_form.html.erb
<%= form_with(model: ethogram, local: true) do |form| %>
  <% if ethogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ethogram.errors.count, "error") %> prohibited this ethogram from being saved:</h2>

      <ul>
      <% ethogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ethogram_name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :structure %>
    <%= form.text_area :structure, id: :ethogram, value: (JSON.pretty_generate(ethogram.structure) if ethogram.structure ), class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/ethograms/edit.html.erb
<h1>Editing Ethogram</h1>

<%= render 'form', ethogram: @ethogram %>

<%= link_to 'Show', @ethogram %> |
<%= link_to 'Back', ethograms_path %>

app/views/ethograms/index.html.erb
<h1>Ethograms</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ethograms.each do |ethogram| %>
      <tr>
        <td><%= ethogram.name %></td>
        <td><%= link_to 'Show', ethogram %></td>
        <td><%= link_to 'Edit', edit_ethogram_path(ethogram) %></td>
        <td><%= link_to 'Destroy', ethogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ethogram', new_ethogram_path %>

app/views/ethograms/new.html.erb
<h1>New Ethogram</h1>

<%= render 'form', ethogram: @ethogram %>

<%= link_to 'Back', ethograms_path %>

app/views/ethograms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @ethogram.name %>
</p>

<%= link_to 'Edit', edit_ethogram_path(@ethogram) %> |
<%= link_to 'Back', ethograms_path %>

app/views/home/index.html.erb
<div class="dashboard">
  <div class="row row-eq-height">
    <div class="col-6">
      <div class="card">
        <div class="card-block">
          <h3 class="card-title"><%= @num_observations %></h3>
          <%= @num_observations > 1 ? "observations" : "observation" %> uploaded
        </div>
      </div>
    </div>

    <div class="col-6">
      <div class="card">
        <div class="card-block">
          <h3 class="card-title">
            <%- if @latest_observation %>
              <%= time_ago_in_words(@latest_observation.created_at) %> ago
            <%- else %>
              n/a
            <%- end %>
          </h3>
          <p class="card-text">latest observation uploaded</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaveTheAnimalsApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right"
              type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to image_tag('renee-the-panda-small.png'), root_url, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
              <li class="nav-item">
                <%= link_to 'Manage Ethograms', ethograms_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Export Observations', export_observations_path(format: :csv), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Users', users_path, method: :get, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
          <% else %>
              <li class="nav-item">
                <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
              </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <main class="container">

      <%= flash_messages %>

      <div class="content">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
    <div class="card col-lg-4 col-md-6">
      <div class="card-block">
        <ul class="list-group list-group-flush">
          <p class="card-text"><span><b>Email: </b></span><%= user.email %></p>
          <%= link_to 'Destroy', users_path(user.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-danger card-link' %>
        </ul>
      </div>
    </div>
<% end %>